param(
    [switch]$Install,
    [switch]$Remove,
    [switch]$Status,
    [switch]$InstallCmd,
    [switch]$Start,
    [string]$Dir = ""
)

$ErrorActionPreference = "Continue"

if (-not $Dir) {
    $Dir = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
}

$taskName = "Runmote Daemon"
$python = ""
$envVars = @{}

# Try .venv first, then fallback to python in PATH
$venvPython = Join-Path (Join-Path (Join-Path $Dir ".venv") "Scripts") "python.exe"
if (Test-Path $venvPython) {
    $python = $venvPython
} else {
    $python = (Get-Command python -ErrorAction SilentlyContinue).Source
    if (-not $python) {
        $python = (Get-Command python3 -ErrorAction SilentlyContinue).Source
    }
}

if (-not $python) {
    Write-Host "Error: no Python found. Run 'uv sync' in $Dir first."
    exit 1
}

function Install-AutoStart {
    Write-Host "Installing Runmote daemon auto-start..."

    # Write run-daemon.ps1 wrapper
    $wrapperDir = Join-Path $Dir "scripts"
    New-Item -ItemType Directory -Force -Path $wrapperDir | Out-Null
    $wrapperPath = Join-Path $wrapperDir "run-daemon.ps1"

    $logFile = '$env:TEMP\runmote-daemon.log'
    $wrapperLines = @(
        "# Runmote daemon launcher (generated by setup-autostart.ps1)",
        "`$logFile = `"$logFile`""
    )

    if ($env:ACP_DAEMON_TOKEN) {
        $wrapperLines += "`$env:ACP_DAEMON_TOKEN = '$($env:ACP_DAEMON_TOKEN)'"
    }
    if ($env:ACP_DAEMON_ID) {
        $wrapperLines += "`$env:ACP_DAEMON_ID = '$($env:ACP_DAEMON_ID)'"
    }
    if ($env:ACP_RELAY_URL) {
        $wrapperLines += "`$env:ACP_RELAY_URL = '$($env:ACP_RELAY_URL)'"
    }
    if ($env:ACP_RELAY_PUBLIC_URL) {
        $wrapperLines += "`$env:ACP_RELAY_PUBLIC_URL = '$($env:ACP_RELAY_PUBLIC_URL)'"
    }
    $wrapperLines += "`$env:PYTHONIOENCODING = 'utf-8'"
    # Extended PATH for agent detection (matching Linux systemd service)
    $userHome = '$env:USERPROFILE'
    $wrapperLines += "# Extended PATH for agent detection`n" +
        "`$agentPaths = @(`"$userHome\.local\bin`", `"$userHome\AppData\Roaming\npm`", `"$userHome\.opencode\bin`", `"$userHome\.cargo\bin`", `"$userHome\.bun\bin`")`n" +
        "`$env:Path = (`$agentPaths + `$env:Path.Split(';') | Where-Object { `$_ -and (Test-Path `$_ -ErrorAction SilentlyContinue) }) -join ';'"

    $errFile = '$env:TEMP\runmote-daemon.err'
    $wrapperLines += "`$errFile = `"$errFile`""
    $wrapperLines += "Start-Process -WindowStyle Hidden -FilePath `"$python`" -ArgumentList `"-m`", `"src.daemon.main`" -WorkingDirectory `"$Dir`" -RedirectStandardOutput `$logFile -RedirectStandardError `$errFile"

    Set-Content -Path $wrapperPath -Value ($wrapperLines -join "`r`n")
    Write-Host "  wrapper created: $wrapperPath"

    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

    if ($isAdmin) {
        # Admin: register scheduled task (runs at login, survives reboots)
        $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$wrapperPath`""
        $trigger = New-ScheduledTaskTrigger -AtLogOn
        $trigger.Delay = "PT15S"
        $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 1)
        Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Force | Out-Null
        Write-Host "  scheduled task created: $taskName"
    } else {
        # Non-admin: use HKCU Run key (no admin required)
        $runKey = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run"
        $regValue = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$wrapperPath`""
        Set-ItemProperty -Path $runKey -Name "Runmote Daemon" -Value $regValue
        Write-Host "  startup registry entry added (HKCU Run key)"

        # Also add a shortcut to the Startup folder as a visual backup
        $startupFolder = [Environment]::GetFolderPath("Startup")
        $shortcutPath = Join-Path $startupFolder "Runmote Daemon.lnk"
        $shell = New-Object -ComObject WScript.Shell
        $shortcut = $shell.CreateShortcut($shortcutPath)
        $shortcut.TargetPath = "powershell.exe"
        $shortcut.Arguments = "-NoProfile -ExecutionPolicy Bypass -File `"$wrapperPath`""
        $shortcut.WindowStyle = 7
        $shortcut.Description = "Runmote Daemon"
        $shortcut.Save()
        Write-Host "  startup folder shortcut added"

        Write-Host "  (scheduled task skipped — run PowerShell as Administrator for Task Scheduler)"
    }

    # Create runmote.cmd in user PATH
    Install-RunmoteCmd
}

function Remove-AutoStart {
    Write-Host "Removing Runmote daemon auto-start..."

    # Remove scheduled task (admin) — silently ignore if not admin
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue | Out-Null
    Write-Host "  scheduled task removed: $taskName"

    # Remove HKCU Run key (non-admin)
    $runKey = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run"
    Remove-ItemProperty -Path $runKey -Name "Runmote Daemon" -ErrorAction SilentlyContinue | Out-Null
    Write-Host "  registry entry removed"

    # Remove Startup folder shortcut
    $startupFolder = [Environment]::GetFolderPath("Startup")
    $shortcutPath = Join-Path $startupFolder "Runmote Daemon.lnk"
    if (Test-Path $shortcutPath) {
        Remove-Item $shortcutPath -Force
        Write-Host "  startup folder shortcut removed"
    }

    $wrapperPath = Join-Path (Join-Path $Dir "scripts") "run-daemon.ps1"
    if (Test-Path $wrapperPath) {
        Remove-Item $wrapperPath -Force
        Write-Host "  wrapper removed"
    }

    Remove-RunmoteCmd
}

function Get-AutoStartStatus {
    $found = $false

    # Check scheduled task
    try {
        $task = Get-ScheduledTask -TaskName $taskName -ErrorAction Stop
        Write-Host "Runmote daemon: ENABLED (Task Scheduler)"
        Write-Host "  State: $($task.State)"
        Write-Host "  Next Run: $($task.NextRunTime)"
        $found = $true
    } catch {
        Write-Host "Runmote daemon: Task Scheduler — NOT INSTALLED"
    }

    # Check HKCU Run key
    $runKey = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run"
    $regValue = Get-ItemProperty -Path $runKey -Name "Runmote Daemon" -ErrorAction SilentlyContinue
    if ($regValue) {
        Write-Host "Runmote daemon: ENABLED (HKCU Run key)"
        Write-Host "  Value: $($regValue.'Runmote Daemon')"
        $found = $true
    } else {
        Write-Host "Runmote daemon: HKCU Run key — NOT INSTALLED"
    }

    # Check Startup folder
    $startupFolder = [Environment]::GetFolderPath("Startup")
    $shortcutPath = Join-Path $startupFolder "Runmote Daemon.lnk"
    if (Test-Path $shortcutPath) {
        Write-Host "Runmote daemon: ENABLED (Startup Folder)"
        $found = $true
    } else {
        Write-Host "Runmote daemon: Startup Folder — NOT INSTALLED"
    }

    if (-not $found) {
        Write-Host "Runmote daemon: NOT INSTALLED"
    }
}

function Install-RunmoteCmd {
    $binDir = Join-Path (Join-Path $env:USERPROFILE ".local") "bin"
    New-Item -ItemType Directory -Force -Path $binDir | Out-Null
    $cmdPath = Join-Path $binDir "runmote.cmd"

    $psScriptPath = Join-Path (Join-Path $Dir "scripts") "runmote.ps1"
    $cmdLines = @(
        "@echo off",
        "powershell -NoProfile -ExecutionPolicy Bypass -File `"$psScriptPath`" %*"
    )

    Set-Content -Path $cmdPath -Value ($cmdLines -join "`r`n")
    Write-Host "  runmote command added to PATH: $cmdPath"
}

function Remove-RunmoteCmd {
    $cmdPath = Join-Path (Join-Path (Join-Path $env:USERPROFILE ".local") "bin") "runmote.cmd"
    if (Test-Path $cmdPath) {
        Remove-Item $cmdPath -Force
        Write-Host "  runmote command removed"
    }
}

# --- Start directly (non-admin, works from CMD) ---
function Start-DaemonDirect {
    Write-Host "Starting Runmote daemon..."
    $logFile = "$env:TEMP\runmote-daemon.log"
    $errFile = "$env:TEMP\runmote-daemon.err"
    $pidFile = "$env:TEMP\runmote-daemon.pid"
    Remove-Item $pidFile -Force -ErrorAction SilentlyContinue

    $env:ACP_DAEMON_ID = if ($env:ACP_DAEMON_ID) { $env:ACP_DAEMON_ID } else { $env:COMPUTERNAME }
    $env:PYTHONIOENCODING = "utf-8"

    $proc = Start-Process -WindowStyle Hidden -FilePath $python -ArgumentList "-m", "src.daemon.main" -WorkingDirectory $Dir -RedirectStandardOutput $logFile -RedirectStandardError $errFile -PassThru
    if ($proc) { $proc.Id | Out-File $pidFile -Force }
    Start-Sleep -Seconds 1
    Write-Host "  Daemon started (PID: $($proc.Id))." -ForegroundColor Green
    Write-Host "  Log: $logFile"
}

# --- Dispatch ---
if ($Install) {
    Install-AutoStart
} elseif ($Remove) {
    Remove-AutoStart
} elseif ($Status) {
    Get-AutoStartStatus
} elseif ($InstallCmd) {
    Install-RunmoteCmd
} elseif ($Start) {
    Start-DaemonDirect
} else {
    Write-Host "Usage: .\setup-autostart.ps1 -Install | -Remove | -Status | -Start | -InstallCmd"
}
