param(
    [switch]$Install,
    [switch]$Remove,
    [switch]$Status,
    [string]$Dir = ""
)

$ErrorActionPreference = "Continue"

if (-not $Dir) {
    $Dir = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
}

$taskName = "Runmote Daemon"
$python = ""
$envVars = @{}

# Try .venv first, then fallback to python in PATH
$venvPython = Join-Path $Dir ".venv" "Scripts" "python.exe"
if (Test-Path $venvPython) {
    $python = $venvPython
} else {
    $python = (Get-Command python -ErrorAction SilentlyContinue).Source
    if (-not $python) {
        $python = (Get-Command python3 -ErrorAction SilentlyContinue).Source
    }
}

if (-not $python) {
    Write-Host "Error: no Python found. Run 'uv sync' in $Dir first."
    exit 1
}

function Install-AutoStart {
    Write-Host "Installing Runmote daemon auto-start..."

    # Write run-daemon.ps1 wrapper
    $wrapperDir = Join-Path $Dir "scripts"
    New-Item -ItemType Directory -Force -Path $wrapperDir | Out-Null
    $wrapperPath = Join-Path $wrapperDir "run-daemon.ps1"

    $logFile = '$env:TEMP\runmote-daemon.log'
    $wrapperLines = @(
        "# Runmote daemon launcher (generated by setup-autostart.ps1)",
        "`$logFile = `"$logFile`""
    )

    if ($env:ACP_DAEMON_TOKEN) {
        $wrapperLines += "`$env:ACP_DAEMON_TOKEN = '$($env:ACP_DAEMON_TOKEN)'"
    }
    if ($env:ACP_DAEMON_ID) {
        $wrapperLines += "`$env:ACP_DAEMON_ID = '$($env:ACP_DAEMON_ID)'"
    }
    if ($env:ACP_RELAY_URL) {
        $wrapperLines += "`$env:ACP_RELAY_URL = '$($env:ACP_RELAY_URL)'"
    }

    $wrapperLines += "Start-Process -NoNewWindow -FilePath `"$python`" -ArgumentList `"-m`", `"src.daemon.main`" -WorkingDirectory `"$Dir`" -RedirectStandardOutput `$logFile -RedirectStandardError `$logFile"

    Set-Content -Path $wrapperPath -Value ($wrapperLines -join "`r`n")
    Write-Host "  wrapper created: $wrapperPath"

    # Register scheduled task
    $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$wrapperPath`""
    $trigger = New-ScheduledTaskTrigger -AtLogOn
    $trigger.Delay = "PT15S"
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 1)

    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Force | Out-Null
    Write-Host "  scheduled task created: $taskName"

    # Create runmote.cmd in user PATH
    Install-RunmoteCmd
}

function Remove-AutoStart {
    Write-Host "Removing Runmote daemon auto-start..."
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue | Out-Null
    Write-Host "  scheduled task removed: $taskName"

    $wrapperPath = Join-Path $Dir "scripts" "run-daemon.ps1"
    if (Test-Path $wrapperPath) {
        Remove-Item $wrapperPath -Force
        Write-Host "  wrapper removed"
    }

    Remove-RunmoteCmd
}

function Get-AutoStartStatus {
    try {
        $task = Get-ScheduledTask -TaskName $taskName -ErrorAction Stop
        Write-Host "Runmote daemon: ENABLED (Task Scheduler)"
        Write-Host "  State: $($task.State)"
        Write-Host "  Next Run: $($task.NextRunTime)"
    } catch {
        Write-Host "Runmote daemon: NOT INSTALLED"
    }
}

function Install-RunmoteCmd {
    $binDir = Join-Path $env:USERPROFILE ".local" "bin"
    New-Item -ItemType Directory -Force -Path $binDir | Out-Null
    $cmdPath = Join-Path $binDir "runmote.cmd"

    $psScriptPath = Join-Path $Dir "scripts" "runmote.ps1"
    $cmdLines = @(
        "@echo off",
        "powershell -NoProfile -ExecutionPolicy Bypass -File `"$psScriptPath`" %*"
    )

    Set-Content -Path $cmdPath -Value ($cmdLines -join "`r`n")
    Write-Host "  runmote command added to PATH: $cmdPath"
}

function Remove-RunmoteCmd {
    $cmdPath = Join-Path $env:USERPROFILE ".local" "bin" "runmote.cmd"
    if (Test-Path $cmdPath) {
        Remove-Item $cmdPath -Force
        Write-Host "  runmote command removed"
    }
}

# --- Dispatch ---
if ($Install) {
    Install-AutoStart
} elseif ($Remove) {
    Remove-AutoStart
} elseif ($Status) {
    Get-AutoStartStatus
} else {
    Write-Host "Usage: .\setup-autostart.ps1 -Install | -Remove | -Status"
}
